ALTER TABLE multipla_escolha
    ADD COLUMN IF NOT EXISTS opcao_a TEXT,
    ADD COLUMN IF NOT EXISTS opcao_b TEXT,
    ADD COLUMN IF NOT EXISTS opcao_c TEXT,
    ADD COLUMN IF NOT EXISTS opcao_d TEXT;
